name: compile

on:
  push:
  pull_request:

jobs:
  compile_linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          libconfig-dev \
          libgtest-dev \
          libopus-dev \
          libsodium-dev \
          libvpx-dev \
          pkg-config \
          libavutil-dev \
          libavcodec-dev \
          libavformat-dev \
          libavfilter-dev \
          libx264-dev \
          libasan6 \
          clang-15 \
          clang-tools-15 \
          libclang-15-dev

      - name: compile binary
        run: |
          clang-15 -O3 -std=c99 \
            -Wall \
            -Wextra \
            -Weverything \
            -g -flto -fPIC tox_generic_bot.c -fno-omit-frame-pointer -fsanitize=address -static-libasan -Wl,-Bstatic $(pkg-config --cflags --libs libsodium) -Wl,-Bdynamic -pthread -o tox_generic_bot

      - name: check binary
        run: |
          ldd tox_generic_bot
          ls -al tox_generic_bot
          ls -hal tox_generic_bot

  compile_nix:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v3
          - name: docker build
            uses: addnab/docker-run-action@v3
            with:
                image: nixos/nix:latest
                options: -v ${{ github.workspace }}:/work
                run: |
                    id;ls -al /work/
                    nix-env --install gcc --prebuilt-only
                    nix-env --install binutils --prebuilt-only
                    nix-env --install libsodium --prebuilt-only
                    gcc --version
                    cd /work/;gcc -O3 -g -fPIC tox_generic_bot.c gcc -g -O3 tox_generic_bot.c -L/nix/store/b7ac47isdc4z1ajln6adz3ppcjs1708b-libsodium-1.0.18/lib -I/nix/store/hyxa8plwvgbj16fi2rlvm2sy6idlkab1-libsodium-1.0.18-dev/include -o tox_generic_bot || echo "fix me"

  compile_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
             brew update
             brew install \
               libconfig \
               libsodium \
               libvpx \
               opus
             id;ls -al;pwd
             gcc --version
             gcc -O3 -std=c99 -g tox_generic_bot.c $(pkg-config --cflags --libs libsodium) -pthread -o tox_generic_bot
             otool -L tox_generic_bot
             ls -hal tox_generic_bot


